name: Build and deploy Node.js app to Azure Web App - almuhammadi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install deps (no audit noise)
        env:
          NPM_CONFIG_AUDIT: "false"
        run: npm ci || npm install

      - name: Build app (ignore ESLint warnings)
        env:
          CI: false
        run: npm run build --if-present

      # If you keep tests but have none, make them pass:
      - name: Test (pass with no tests)
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFCADC9364B04B4699624465CDECCD2E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56204523007F46DD867B3155E376DDC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5F31D6C9868C4337B82A963DF1EB4C50 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'almuhammadi'   # must exactly match Azure Overview name (often includes a suffix)
          # resource-group-name: '<YOUR_RESOURCE_GROUP>'  # optional but recommended to be explicit
          package: .
